// import './typescript/basic-type.ts'
// import './typescript/symbol.ts'
// import './typescript/generics.ts'
// import './typescript/class.js'
// import './typescript/class-02.js'
// import './typescript/class-03.js'
import './typescript/class.ts'